
name: tests

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop


jobs:

  checks:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10"]

    
    name: Python ${{ matrix.python-version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    

    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          activate-environment: qgs
          environment-file: environment.yml
          auto-activate-base: false
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: Run tests
        shell: bash -el {0}
        run: |
          pytest

  status:


    if: ${{ github.event_name == 'pull_request' }}

    name: Pull Request Status
    needs: checks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Issue status
        shell: bash
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Climdyn/qgs/statuses/${{ github.event.pull_request.head.sha }} \
          -d '{"state":"success","target_url":"https://github.com/Climdyn/qgs/commit/${{ github.event.pull_request.head.sha }}","description":"The tests succeeded!","context":"PR-status"}'